### ISSUE TITLE
Add database interactor class

### ISSUE THREAD

**Issue by kpraturu** [GTInventory/IMS#12]
## Story/Task Details
- [x] Create a JavaScript or ReactJS class that handles interaction with the database.

## Acceptance Criteria
- [x] The class should have a function to add an input attribute name and corresponding attribute parameters (like ID, data type, etc.) that are passed into the function to the database. 

- [x] The class should have a function that takes in a string representing an attribute name and gets the corresponding attribute from the database. Returns null if the attribute does not exist in the database.

- [x] The class should have a function that takes in a string representing a part of an attribute name or a full attribute name and returns the closest matches (at most 5) as a list ordered by relevance. If an empty list is returned, that means there were no closest matches.

**Comment by suprabhatgurrala** [comment]
DAO class created, attribute filtering is still not working
