### ISSUE TITLE
As an IT administrator, I want to define a new attribute so that it can be used in an equipment type.

### ISSUE THREAD

**Issue by kpraturu** [GTInventory/IMS#3]
## Story/Task Details
- [x] create a page where the user can manage attributes that is accessible from the main page with an add attributes option

- [x] create an "add attribute" pop up window where the user can input text to denote the name and type of attribute

- [x] when searching for attributes with the attribute search bar, create a results table that is populated with closest matching attributes found in the database

## Acceptance Scenarios
- Given: That I am an IT administrator 
- When: I want to add a new attribute to the system
- Then: I should be able to easily add a new attribute to the system
</br>

- Given: That I am an IT administrator
- When: I want to check if an attribute already exists in the system
- Then: I should be able to search for an attribute and see if results pop up
</br>

- Given: That I am an IT administrator
- When: I want to add a new attribute to the system that already exists
- Then: I should be notified that this attribute already exists

## Done Done Criteria
A user (IT Administrator) is able to add an attribute type to the system.

**Comment by jasonlin1217** [comment]
Created the add attribute popup and made it so that clicking the add attribute button makes the popup appear. The attribute name can be entered and attribute type can be selected in the add attribute popup however the submit button does nothing. It only brings the user back to the manage attributes page.

**Comment by aaronstrickland81** [comment]
Updating to a more realistic estimate since this story encompasses backend and frontend work split between 3 people
