### ISSUE TITLE
As an IT administrator, I want to edit an attribute so that I can update the system as needed.

### ISSUE THREAD

**Issue by aaronstrickland81** [GTInventory/IMS#4]
## Story/Task Details
- [x] Create an attribute detail page where an attribute's details can be viewed
- [x] Create a linked edit page where the attribute can be edited

## Acceptance Criteria
- [x] The application should contain a “manage attributes” page where the user can manage attributes that is accessible from the main page.
- [x] The “manage attributes” page should have a list of all attributes that have been defined in the system.
- [x] The “manage attributes” page should have a search field which allows the user to search for a specific attribute by name.
- [ ] The search field should not accept invalid characters.
- [x] When the user selects an attribute from the page, it should bring the user to the “attribute detail” page which displays the attribute’s details.
- [x] The attribute detail page should have an edit button which brings the user to an “edit attribute” page.
- [x] The “edit attribute” page should have a similar display to the “attribute detail” page, but with editable fields.
- [ ] The fields in the “edit attribute” page should reject invalid input on or before save.
- [ ] When the user selects “Save” on the “edit attribute” page, if the attribute is currently in use by any equipment type, the system should display a warning pop-up informing the user of possible data loss and it should confirm that the user wants to carry out the changes being made.

**Comment by aaronstrickland81** [comment]
Proposed format for issues - to be discussed with team/instructors

**Comment by aaronstrickland81** [comment]
Updated format - This will be proposed format. To be discussed with instructors, using their given format for Sprint 1.

Also moved story to appropriate sprint, was previously misplaced.

**Comment by kpraturu** [comment]
When clicking the attribute search tool on the manage attributes page, a table pops up with attributes that should be clickable. They are currently clickable; however, there is a bug where if you don't type anything into the attribute search bar, the table is not clickable.

**Comment by kpraturu** [comment]
Implemented basic functionality for editing attributes.
